# Generated by Django 5.2.5 on 2025-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in GHS', max_digits=10),
        ),
    ]
